# Generated by Django 5.2.1 on 2025-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('fetch_interval', models.IntegerField(default=60)),
                ('notify', models.BooleanField(default=False)),
            ],
        ),
    ]
