# Generated by Django 5.2.1 on 2025-05-18 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
